---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.lyc-handson-aws.com
  resources:
  - topictens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.lyc-handson-aws.com
  resources:
  - topictens/finalizers
  verbs:
  - update
- apiGroups:
  - app.lyc-handson-aws.com
  resources:
  - topictens/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
